AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: template cloudformation pour le deploiement de fonction lambda et d'API Gateway

Resources:
  demo-dialogflow:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dialogflow.handler
      Runtime: nodejs6.10
      Events:
        WebHook:
          Type: Api
          Properties:
            Path: /
            Method: any
      Environment:
        Variables:
          DEBUG: '*'

